name: CI

on: [push]

permissions:
  contents: write

jobs:

    deploy:
        runs-on: ubuntu-latest
        concurrency:
          group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: Git checkout
              uses: actions/checkout@v3
              with:
                submodules: true
                fetch-depth: 0
            
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'
                
            - name: Install Theme
              run: cd themes/hugo-theme-luna && yarn install --production
                
            - name: Install PostCSS-CLI
              run: npm install postcss-cli -g

            - name: Set up Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: 'latest'
                extended: true

            - name: Build Hugo
              run: hugo --minify 

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public 
